#!/bin/bash

if [ -z $1 ]; then
  echo "usage: $0 host cmd [args...]"
  exit 1
fi

# Do not attach stdin if running in an environment without (e.g., GitHub Actions)
it=$(test -t 0 && echo "-it" || echo "-t")

docker exec $it mininet /mininet/host-cmd $@
