#!/bin/bash
docker run --rm --network host \
  docker.pkg.github.com/opennetworkinglab/ngsdn-tutorial/gnmi-cli:latest $@ |
  docker run --rm -i \
  docker.pkg.github.com/opennetworkinglab/ngsdn-tutorial/yang-tools:latest oc-pb-decoder |
  less
