#!/bin/bash

if [ -z $1 ]; then
  echo "usage: $0 cmd [args...]"
  exit 1
fi

sshpass -procks ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -o LogLevel=ERROR -p 8101 onos@localhost "$@"
